In [25]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
import numpy as np
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import  precision_score, recall_score, f1_score, classification_report
from sklearn.metrics import confusion_matrix
from catboost import CatBoostClassifier
import lightgbm as lgb
import xgboost as xgb

In [2]:
from sklearn.dummy import DummyClassifier

In [6]:
dataset = pd.read_csv('csv/uspevaemost_nakop_bez_perevedennih_raw1.csv')
# dataset = dataset[dataset['Квалификация'] != 3]
# dataset = dataset[dataset['Квалификация'] != 4]
data = dataset.iloc[:, :-1]
target = dataset.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3)

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [138]:
data.head()

Семестр  Форма обучения  Квалификация  зачет сразу  \
0        1               2             0          6.0   
1        2               2             0          5.0   
2        3               2             0          2.0   
3        4               2             0          4.0   
4        5               2             0          5.0   

   удовлетворительно сразу  хорошо сразу  отлично сразу  зачет с исправлением  \
0                      0.0           1.0            1.0                   0.0   
1                      1.0           0.0            2.0                   0.0   
2                      0.0           2.0            1.0                   0.0   
3                      0.0           0.0            2.0                   0.0   
4                      0.0           2.0            0.0                   0.0   

   удовлетворительно с исправлением  хорошо с исправлением  ...  \
0                               0.0                    0.0  ...   
1                               0.0                    1.0  ...   
2                               0.0                    1.0  ...   
3                               0.0                    0.0  ...   
4                               0.0                    1.0  ...   

   Накоп удовлетворительно сразу  Накоп хорошо сразу  Накоп отлично сразу  \
0                            0.0                 1.0                  1.0   
1                            1.0                 1.0                  3.0   
2                            1.0                 3.0                  4.0   
3                            1.0                 3.0                  6.0   
4                            1.0                 5.0                  6.0   

   Накоп зачет с исправлением  Накоп удовлетворительно с исправлением  \
0                         0.0                                     0.0   
1                         0.0                                     0.0   
2                         0.0                                     0.0   
3                         0.0                                     0.0   
4                         0.0                                     0.0   

   Накоп хорошо с исправлением  Накоп отлично с исправлением  \
0                          0.0                           0.0   
1                          1.0                           0.0   
2                          2.0                           0.0   
3                          2.0                           1.0   
4                          3.0                           1.0   

   Накоп незачет до исправления  Накоп зачет до исправления  \
0                           0.0                         0.0   
1                           0.0                         0.0   
2                           0.0                         0.0   
3                           0.0                         0.0   
4                           0.0                         0.0   

   Накоп удовлетворительно до исправления  
0                                     0.0  
1                                     1.0  
2                                     2.0  
3                                     3.0  
4                                     4.0  

[5 rows x 26 columns]

In [24]:
data.describe()

Семестр  Форма обучения  Квалификация  незачет сразу  \
count  20165.000000    20165.000000  20165.000000        20165.0   
mean       4.065807        0.581304      0.563452            0.0   
std        2.527685        0.904647      0.959507            0.0   
min        1.000000        0.000000      0.000000            0.0   
25%        2.000000        0.000000      0.000000            0.0   
50%        3.000000        0.000000      0.000000            0.0   
75%        6.000000        2.000000      1.000000            0.0   
max       11.000000        2.000000      3.000000            0.0   

        зачет сразу  удовлетворительно сразу  хорошо сразу  отлично сразу  \
count  20165.000000             20165.000000  20165.000000   20165.000000   
mean       3.950012                 0.760476      1.253360       1.118324   
std        1.630394                 1.135160      1.209026       1.338356   
min        0.000000                 0.000000      0.000000       0.000000   
25%        3.000000                 0.000000      0.000000       0.000000   
50%        4.000000                 0.000000      1.000000       1.000000   
75%        5.000000                 1.000000      2.000000       2.000000   
max       11.000000                 8.000000     11.000000      13.000000   

       зачет с исправлением  удовлетворительно с исправлением  ...  \
count          20165.000000                      20165.000000  ...   
mean               0.004364                          0.033028  ...   
std                0.098997                          0.187647  ...   
min                0.000000                          0.000000  ...   
25%                0.000000                          0.000000  ...   
50%                0.000000                          0.000000  ...   
75%                0.000000                          0.000000  ...   
max                5.000000                          3.000000  ...   

       Накоп удовлетворительно сразу  Накоп хорошо сразу  Накоп отлично сразу  \
count                   20165.000000        20165.000000         20165.000000   
mean                        4.176048            6.015522             4.274585   
std                         6.208828            5.415883             5.308143   
min                         0.000000            0.000000             0.000000   
25%                         0.000000            2.000000             1.000000   
50%                         1.000000            5.000000             2.000000   
75%                         6.000000            9.000000             6.000000   
max                        64.000000           38.000000            42.000000   

       Накоп зачет с исправлением  Накоп удовлетворительно с исправлением  \
count                20165.000000                            20165.000000   
mean                     0.020035                                0.151401   
std                      0.224460                                0.512334   
min                      0.000000                                0.000000   
25%                      0.000000                                0.000000   
50%                      0.000000                                0.000000   
75%                      0.000000                                0.000000   
max                     12.000000                                7.000000   

       Накоп хорошо с исправлением  Накоп отлично с исправлением  \
count                 20165.000000                  20165.000000   
mean                      0.361914                      0.468535   
std                       0.783900                      0.913413   
min                       0.000000                      0.000000   
25%                       0.000000                      0.000000   
50%                       0.000000                      0.000000   
75%                       0.000000                      1.000000   
max                       7.000000                      8.000000   

       Накоп незачет до исправления  

In [15]:
target.shape

(20165,)

In [16]:
target[target==1].sum()

3341

In [17]:
target[target == 0].shape

(16824,)

In [23]:
clf = DummyClassifier(strategy='most_frequent')
clf.fit(X_train, y_train)

DummyClassifier(strategy='most_frequent')

In [24]:
y_pred = clf.predict(X_test)
print("Число ошибочно классифицированных образцов DummyClassifier: % d" % (y_test != y_pred).sum())
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=target_name))

print()
print('Логик регрессион')
print('Вероятность моего отчисления за первый семестр:',clf.predict(pd.read_csv('uspevaemost_nakop_My.csv').iloc[:1,:])[:, 1] * 100)
print('Вероятность моего отчисления за второй семестр:',clf.predict(pd.read_csv('uspevaemost_nakop_My.csv').iloc[1:2,:])[:, 1] * 100)
print('Вероятность моего отчисления за третий семестр:',clf.predict(pd.read_csv('uspevaemost_nakop_My.csv').iloc[2:3,:])[:, 1] * 100)
print('Вероятность моего отчисления за четвертый семестр:',clf.predict(pd.read_csv('uspevaemost_nakop_My.csv').iloc[3:4,:])[:, 1] * 100)
print()

Число ошибочно классифицированных образцов DummyClassifier:  999
0.8348760330578512
                 precision    recall  f1-score   support

0 - не отчислен       0.83      1.00      0.91      5051
       Отчислен       0.00      0.00      0.00       999

       accuracy                           0.83      6050
      macro avg       0.42      0.50      0.46      6050
   weighted avg       0.70      0.83      0.76      6050



C:\Users\fluke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fluke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\fluke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1469

In [12]:
lr = LogisticRegression(C=1000.0, max_iter=1000000000)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

target_name = ['0 - не отчислен', 'Отчислен']
print(classification_report(y_test, y_pred, target_names=target_name))
print(accuracy_score(y_test, y_pred))
confusion_matrix(y_test, y_pred)

print(accuracy_score(y_test, y_pred))

print()
print('Логик регрессион')
print('Вероятность моего отчисления за первый семестр:',lr.predict_proba(pd.read_csv('csv/uspevaemost_nakop_My.csv').iloc[:1,:])[:, 1] * 100)
print('Вероятность моего отчисления за второй семестр:',lr.predict_proba(pd.read_csv('csv/uspevaemost_nakop_My.csv').iloc[1:2,:])[:, 1] * 100)
print('Вероятность моего отчисления за третий семестр:',lr.predict_proba(pd.read_csv('csv/uspevaemost_nakop_My.csv').iloc[2:3,:])[:, 1] * 100)
print('Вероятность моего отчисления за четвертый семестр:',lr.predict_proba(pd.read_csv('csv/uspevaemost_nakop_My.csv').iloc[3:4,:])[:, 1] * 100)


                 precision    recall  f1-score   support

0 - не отчислен       0.89      0.99      0.93      5019
       Отчислен       0.88      0.37      0.53      1031

       accuracy                           0.88      6050
      macro avg       0.88      0.68      0.73      6050
   weighted avg       0.88      0.88      0.86      6050

0.8846280991735537


array([[4966,   53],
       [ 645,  386]], dtype=int64)

In [161]:
best = np.zeros([3])



for i in range(1, 15):
        for j in range(1, 3):
            model = CatBoostClassifier(iterations=1000, task_type="GPU", devices='0:1', depth=i,        # Глубина деревьев
                                    learning_rate=1/(10**j),  # Скорость обучения
                                    loss_function='Logloss',  # Функция потерь для задачи классификации
                                    logging_level='Silent')
            model.fit(X_train_std, y_train)

            y_pred = model.predict(X_test_std)

            accuracy = accuracy_score(y_test, y_pred)
            report = classification_report(y_test, y_pred)

            info = np.array([f'Глубина {i}', f'Скорость обучения {1/(10**j)}', accuracy])
            print(info)
            best = np.vstack((best, info))

max_row_index = np.argmax(best[:, 2])

# Extract the row with the maximum value
max_row = best[max_row_index, :]

print("Row with the maximum value in column {}: {}".format(2, max_row))


['Глубина 1' 'Скорость обучения 0.1' '0.8505506030414264']


KeyboardInterrupt: 

In [162]:
model = CatBoostClassifier(iterations=1000, task_type="GPU", devices='0:1', depth=8,        # Глубина деревьев
                                    learning_rate=0.1,  # Скорость обучения
                                    loss_function='Logloss',  # Функция потерь для задачи классификации
                                    logging_level='Silent')
model.fit(X_train_std, y_train)

y_pred = model.predict(X_test_std)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(accuracy)

print(report)

KeyboardInterrupt: 

In [137]:
confusion_matrix(y_test, y_pred)


array([[4650,  116],
       [ 588,  367]], dtype=int64)

In [64]:
sum(y_pred == 1)

601

In [185]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier = DecisionTreeClassifier()
tree_classifier.fit(X_train_std, y_train)

# Make predictions
tree_predictions = tree_classifier.predict(X_test_std)

# Evaluate the model
tree_accuracy = accuracy_score(y_test, tree_predictions)
print(f"Decision Tree Accuracy: {tree_accuracy}")

report = classification_report(y_test,  tree_predictions)
print(report)
confusion_matrix(y_test, tree_predictions)

Decision Tree Accuracy: 0.8751966439433665
              precision    recall  f1-score   support

           0       0.91      0.94      0.93      4689
           1       0.69      0.56      0.62      1032

    accuracy                           0.88      5721
   macro avg       0.80      0.75      0.77      5721
weighted avg       0.87      0.88      0.87      5721



array([[4429,  260],
       [ 454,  578]], dtype=int64)

In [186]:
from sklearn.ensemble import RandomForestClassifier

# Create and train a random forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100)
rf_classifier.fit(X_train, y_train)

# Make predictions
rf_predictions = rf_classifier.predict(X_test)

# Evaluate the model
rf_accuracy = accuracy_score(y_test, rf_predictions)
print(f"Random Forest Accuracy: {rf_accuracy}")
report = classification_report(y_test, y_pred)
print(report)
confusion_matrix(y_test, y_pred)

Random Forest Accuracy: 0.8937248732739032
              precision    recall  f1-score   support

           0       0.89      0.99      0.93      4689
           1       0.90      0.42      0.58      1032

    accuracy                           0.89      5721
   macro avg       0.89      0.71      0.76      5721
weighted avg       0.89      0.89      0.87      5721



array([[4638,   51],
       [ 594,  438]], dtype=int64)

In [188]:
from sklearn.svm import SVC

# Create and train an SVM classifier
svm_classifier = SVC()
svm_classifier.fit(X_train_std, y_train)

# Make predictions
svm_predictions = svm_classifier.predict(X_test_std)

# Evaluate the model
svm_accuracy = accuracy_score(y_test, svm_predictions)
print(f"SVM Accuracy: {svm_accuracy}")
report = classification_report(y_test, svm_predictions)
print(report)
confusion_matrix(y_test, svm_predictions)

SVM Accuracy: 0.8835867855270058
              precision    recall  f1-score   support

           0       0.88      1.00      0.93      4689
           1       0.96      0.37      0.54      1032

    accuracy                           0.88      5721
   macro avg       0.92      0.68      0.73      5721
weighted avg       0.89      0.88      0.86      5721



array([[4671,   18],
       [ 648,  384]], dtype=int64)

In [198]:
from sklearn.naive_bayes import GaussianNB


    

# Create and train a Gaussian Naive Bayes classifier
nb_classifier = GaussianNB()
nb_classifier.fit(X_train_std, y_train)

# Make predictions
nb_predictions = nb_classifier.predict(X_test_std)

# Evaluate the model
nb_accuracy = accuracy_score(y_test, nb_predictions)
print(f"Naive Bayes Accuracy: {nb_accuracy}")
report = classification_report(y_test, nb_predictions)
print(report)
confusion_matrix(y_test, nb_predictions)

Naive Bayes Accuracy: 0.8655829400454466
              precision    recall  f1-score   support

           0       0.87      0.98      0.92      4689
           1       0.80      0.34      0.48      1032

    accuracy                           0.87      5721
   macro avg       0.83      0.66      0.70      5721
weighted avg       0.86      0.87      0.84      5721



array([[4600,   89],
       [ 680,  352]], dtype=int64)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Create and train a KNN classifier with k=5 (you can adjust k)
for i in range(1, 10):
    knn_classifier = KNeighborsClassifier(n_neighbors=i)
    knn_classifier.fit(X_train_std, y_train)

    # Make predictions
    knn_predictions = knn_classifier.predict(X_test_std)

    # Evaluate the model
    knn_accuracy = accuracy_score(y_test, knn_predictions)
    print(f"KNN Accuracy: {knn_accuracy}")
    report = classification_report(y_test, knn_predictions)
    print(report)
    confusion_matrix(y_test, knn_predictions)

KNN Accuracy: 0.859465128474043
              precision    recall  f1-score   support

           0       0.90      0.93      0.92      4689
           1       0.63      0.53      0.58      1032

    accuracy                           0.86      5721
   macro avg       0.77      0.73      0.75      5721
weighted avg       0.85      0.86      0.85      5721

KNN Accuracy: 0.8706519839188953
              precision    recall  f1-score   support

           0       0.87      0.98      0.93      4689
           1       0.83      0.36      0.50      1032

    accuracy                           0.87      5721
   macro avg       0.85      0.67      0.71      5721
weighted avg       0.87      0.87      0.85      5721

KNN Accuracy: 0.8723999300821534
              precision    recall  f1-score   support

           0       0.89      0.97      0.93      4689
           1       0.74      0.45      0.56      1032

    accuracy                           0.87      5721
   macro avg       0.81      0

Row with the maximum value in column 2: ['Глубина 10' 'Скорость обучения 0.01' '0.9127774864534173']

In [40]:
import numpy as np

# Create an initial NumPy array
arr = np.array([1, 2, 3])

# Append a single element


# Append multiple elements (as a list)
new_elements = [5, 6, 7]
arr = np.vstack((arr, new_elements))

print(arr)

[[1 2 3]
 [5 6 7]]


In [24]:
train_data = lgb.Dataset(X_train_std, label=y_train)
test_data = lgb.Dataset(X_test_std, label=y_test, reference=train_data)

# Определяем параметры модели
params = {
    'objective': 'binary',  # для задачи бинарной классификации
    'boosting_type': 'gbdt',
    'metric': 'binary_logloss',  # метрика качества
    'num_leaves': 50,
    'learning_rate': 0.01,
    'feature_fraction': 0.9
}

# Обучаем модель
num_round = 1000  # количество итераций обучения
bst = lgb.train(params, train_data, num_round, valid_sets=[test_data])

# Предсказываем на тестовом наборе данных
y_pred = bst.predict(X_test_std, num_iteration=bst.best_iteration)

# Оцениваем качество модели
y_pred_binary = np.round(y_pred)  # преобразуем вероятности в бинарные предсказания
accuracy = accuracy_score(y_test, y_pred_binary)
print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(report)
confusion_matrix(y_test, y_pred_binary)

[LightGBM] [Info] Number of positive: 2325, number of negative: 11023
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002899 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 380
[LightGBM] [Info] Number of data points in the train set: 13348, number of used features: 27
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.174183 -> initscore=-1.556264
[LightGBM] [Info] Start training from score -1.556264
Accuracy: 0.9141758433840238
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.98      0.95      4809
           1       0.86      0.54      0.67       912

    accuracy                           0.91      5721
   macro avg       0.89      0.76      0.81      5721
weighted avg       0.91      0.91      0.90      5721



array([[4713,   96],
       [ 395,  517]], dtype=int64)

In [28]:
params = {
    'objective': 'binary:logistic',  # для задачи бинарной классификации
    'max_depth': 3,
    'learning_rate': 0.1,
    'n_estimators': 1000,
    'eval_metric': 'logloss'
}

# Создаем объект DMatrix для данных
train_data = xgb.DMatrix(X_train_std, label=y_train)
test_data = xgb.DMatrix(X_test_std, label=y_test)

# Обучаем модель с ранней остановкой (early stopping)
watchlist = [(test_data, 'eval'), (train_data, 'train')]
num_round = 1000  # большое количество итераций
bst = xgb.train(params, train_data, num_round, evals=watchlist, early_stopping_rounds=10)

# Предсказываем на тестовом наборе данных
y_pred = bst.predict(test_data)

# Оцениваем качество модели
y_pred_binary = np.round(y_pred)  # преобразуем вероятности в бинарные предсказания
accuracy = accuracy_score(y_test, y_pred_binary)
print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(report)
confusion_matrix(y_test, y_pred_binary)

[0]	eval-logloss:0.42092	train-logloss:0.43862
[1]	eval-logloss:0.40138	train-logloss:0.41816
[2]	eval-logloss:0.38580	train-logloss:0.40161
[3]	eval-logloss:0.37321	train-logloss:0.38843
[4]	eval-logloss:0.36260	train-logloss:0.37748
[5]	eval-logloss:0.35356	train-logloss:0.36787
[6]	eval-logloss:0.34593	train-logloss:0.35966
[7]	eval-logloss:0.33895	train-logloss:0.35262


[8]	eval-logloss:0.33272	train-logloss:0.34624
[9]	eval-logloss:0.32766	train-logloss:0.34072
[10]	eval-logloss:0.32286	train-logloss:0.33590
[11]	eval-logloss:0.31803	train-logloss:0.33073
[12]	eval-logloss:0.31362	train-logloss:0.32619
[13]	eval-logloss:0.30983	train-logloss:0.32182
[14]	eval-logloss:0.30636	train-logloss:0.31852
[15]	eval-logloss:0.30296	train-logloss:0.31499
[16]	eval-logloss:0.29984	train-logloss:0.31190
[17]	eval-logloss:0.29726	train-logloss:0.30881
[18]	eval-logloss:0.29519	train-logloss:0.30644
[19]	eval-logloss:0.29265	train-logloss:0.30382
[20]	eval-logloss:0.29057	train-logloss:0.30187
[21]	eval-logloss:0.28872	train-logloss:0.29964
[22]	eval-logloss:0.28695	train-logloss:0.29764
[23]	eval-logloss:0.28525	train-logloss:0.29568
[24]	eval-logloss:0.28358	train-logloss:0.29374
[25]	eval-logloss:0.28221	train-logloss:0.29215
[26]	eval-logloss:0.28100	train-logloss:0.29066
[27]	eval-logloss:0.27975	train-logloss:0.28906
[28]	eval-logloss:0.27804	train-logloss:0.

C:\Users\fluke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\xgboost\data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
C:\Users\fluke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\xgboost\core.py:160: UserWarning: [21:08:44] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0cec3277c4d9d0165-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "n_estimators" } are not used.

  warnings.warn(smsg, UserWarning)


[62]	eval-logloss:0.25572	train-logloss:0.25952
[63]	eval-logloss:0.25539	train-logloss:0.25921
[64]	eval-logloss:0.25515	train-logloss:0.25897
[65]	eval-logloss:0.25482	train-logloss:0.25853
[66]	eval-logloss:0.25445	train-logloss:0.25802
[67]	eval-logloss:0.25420	train-logloss:0.25776
[68]	eval-logloss:0.25403	train-logloss:0.25748
[69]	eval-logloss:0.25367	train-logloss:0.25701
[70]	eval-logloss:0.25348	train-logloss:0.25682
[71]	eval-logloss:0.25314	train-logloss:0.25634
[72]	eval-logloss:0.25267	train-logloss:0.25585
[73]	eval-logloss:0.25258	train-logloss:0.25566
[74]	eval-logloss:0.25235	train-logloss:0.25538
[75]	eval-logloss:0.25210	train-logloss:0.25505
[76]	eval-logloss:0.25167	train-logloss:0.25449
[77]	eval-logloss:0.25155	train-logloss:0.25435
[78]	eval-logloss:0.25146	train-logloss:0.25412
[79]	eval-logloss:0.25116	train-logloss:0.25366
[80]	eval-logloss:0.25081	train-logloss:0.25304
[81]	eval-logloss:0.25075	train-logloss:0.25289
[82]	eval-logloss:0.25055	train-logloss:

array([[4718,   91],
       [ 415,  497]], dtype=int64)

In [18]:
y_test[y_test == 1].shape

(999,)

In [21]:
sum(y_pred == 1)

442

In [6]:
for column, coef in zip(data.columns, lr.coef_[0]):
    print(f'Важность признака {column} равна {coef}')


Важность признака Семестр равна -0.956222860367033
Важность признака Форма обучения равна 0.1598202852549684
Важность признака Квалификация равна -0.29194072457118514
Важность признака незачет сразу равна 0.0
Важность признака зачет сразу равна -0.15757901100135419
Важность признака удовлетворительно сразу равна 0.08299480598579387
Важность признака хорошо сразу равна -0.20043796394497296
Важность признака отлично сразу равна -0.40053436044570895
Важность признака зачет с исправлением равна 0.308135208540496
Важность признака удовлетворительно с исправлением равна -0.20779939075103881
Важность признака хорошо с исправлением равна -0.0123359071861901
Важность признака отлично с исправлением равна -0.3164868078049016
Важность признака незачет до исправления равна 0.13711429429267727
Важность признака зачет до исправления равна -0.17437642924232838
Важность признака удовлетворительно до исправления равна -0.022385418060579955
Важность признака хорошо до исправления равна -0.16883934419133

In [29]:
lr.coef_[0]

array([-8.49852229e-01,  1.08975607e-01, -2.72577701e-01,  0.00000000e+00,
       -1.76052968e-01,  1.08859017e-01, -1.81742184e-01, -3.82745231e-01,
        1.66923713e-01, -1.07898967e-01,  7.39549741e-02, -3.42514923e-01,
        6.39133728e-02, -2.60078462e-01, -1.82990766e-04, -1.31871222e-02,
        6.46200397e+00, -1.49514477e-02,  1.38186829e-01,  1.72984895e-01,
        2.97954693e-02, -6.42259076e-01, -4.95371751e-01, -2.99388069e-01,
       -2.83218758e-01,  7.09152083e-01,  6.05729588e-01, -8.11245553e-02])